### PR TITLE
Rename to grunt-pug-i18n

### PR DESCRIPTION
**Pull request by michelegera**
`grunt-jade-i18n` is not working properly since its dependency `grunt-contrib-jade` has been renamed to `grunt-contrib-pug` as per https://github.com/pugjs/pug/issues/2184.

This PR updates the dependency and renames everything to Pug, as suggested in https://github.com/AdesisNetlife/grunt-jade-i18n/issues/33. The only things it doesn’t rename are the module name and repository in `package.json`.

### CODE REVIEW

**Comment by h2non** [comment]
Thank you.

**Comment by h2non** [comment]
Will release the package in npm tomorrow

**Comment by michelegera** [comment]
That’s great, thanks @h2non!

**Comment by Lowgain** [comment]
Awesome, thanks!

**Comment by h2non** [comment]
Done! You can fetch it from [npm](https://www.npmjs.com/package/grunt-pug-i18n) now.
```bash
npm i grunt-pug-i18n --save-dev
```

**Pull request merged**
